const ageQuotes = [
        { age: 0, quote: "The adventure of a lifetime begins at one. Welcome to the world, little one!" },
        { age: 1, quote: "The adventure of a lifetime begins at one. Welcome to the world, little one!" },
        { age: 2, quote: "Two years old and full of wonder. Every day is a new discovery!" },
        { age: 3, quote: "At three, you're a little explorer. Embrace the joy of exploration!" },
        { age: 4, quote: "Four years old and full of energy. Your curiosity knows no bounds!" },
        { age: 5, quote: "Five years old and ready for adventure. Embrace the joy of growing up!" },
        { age: 6, quote: "Six years old and making memories. Your laughter fills the world with happiness!" },
        { age: 7, quote: "Seven years old and full of dreams. Your imagination knows no limits!" },
        { age: 8, quote: "Eight years old and full of creativity. Your ideas are as boundless as the sky!" },
        { age: 9, quote: "Nine years old and on the brink of double digits. Your journey is just beginning!" },
        { age: 10, quote: "Ten years old! Double digits bring new adventures and exciting milestones." },
        { age: 11, quote: "Eleven years old and blooming with potential. Keep reaching for the stars!" },
        { age: 12, quote: "Twelve years old and on the cusp of teenagehood. Cherish the moments of innocence!" },
        { age: 13, quote: "Thirteen years old, officially a teenager! Embrace the journey of self-discovery." },
        { age: 14, quote: "Fourteen years old and navigating the maze of adolescence. You've got this!" },
        { age: 15, quote: "Fifteen years old and blossoming into your unique self. Your individuality is your strength!" },
        { age: 16, quote: "Sweet sixteen! You're stepping into a world of possibilities and self-discovery." },
        { age: 17, quote: "Seventeen years old and on the brink of adulthood. Embrace the challenges and growth!" },
        { age: 18, quote: "Eighteen years old! Welcome to adulthood. Navigate with courage, and enjoy the ride." },
        { age: 19, quote: "Nineteen years old and on the threshold of new adventures. Your journey continues!" },
        { age: 20, quote: "Twenty years old! A new decade brings fresh opportunities and experiences." },
        { age: 21, quote: "Twenty-one years old, officially an adult! Cheers to the freedom and responsibilities ahead." },
        { age: 22, quote: "Twenty-two years old and navigating the complexities of early adulthood. You're building your path!" },
        { age: 23, quote: "Twenty-three years old and thriving. Your journey is uniquely yours!" },
        { age: 24, quote: "Twenty-four years old and shaping your destiny. Keep pursuing your dreams!" },
        { age: 25, quote: "A quarter-century of life! Your journey is unfolding, and the best is yet to come." },
        { age: 26, quote: "Twenty-six years old and in the prime of life. Make every moment count!" },
        { age: 27, quote: "Twenty-seven years old and thriving. Your resilience is your strength!" },
        { age: 28, quote: "Twenty-eight years old and building a life of purpose. Continue to pursue your passions!" },
        { age: 29, quote: "Twenty-nine years old and embracing the journey. Your potential is limitless!" },
        { age: 30, quote: "Thirty years old! The adventure continues. Cherish the memories and create new ones!" },
        { age: 31, quote: "Thirty-one years old and navigating the thirties. Your experiences shape your wisdom!" },
        { age: 32, quote: "Thirty-two years old and flourishing. Your journey is uniquely yours!" },
        { age: 33, quote: "Thirty-three years old and thriving. Your resilience is your strength!" },
        { age: 34, quote: "Thirty-four years old and building a life of purpose. Continue to pursue your passions!" },
        { age: 35, quote: "Thirty-five years old! A milestone of growth and accomplishment. Keep shining!" },
        { age: 36, quote: "Thirty-six years old and embracing the journey. Your potential is limitless!" },
        { age: 37, quote: "Thirty-seven years old and thriving. Your resilience is your strength!" },
        { age: 38, quote: "Thirty-eight years old and building a life of purpose. Continue to pursue your passions!" },
        { age: 39, quote: "Thirty-nine years old and embracing the journey. Your potential is limitless!" },
        { age: 40, quote: "Forty years old and fabulous! Celebrate the experiences that have shaped you." },
        { age: 41, quote: "Forty-one years old and thriving. Your journey is uniquely yours!" },
        { age: 42, quote: "Forty-two years old and flourishing. Your resilience is your strength!" },
        { age: 43, quote: "Forty-three years old and building a life of purpose. Continue to pursue your passions!" },
        { age: 44, quote: "Forty-four years old and embracing the journey. Your potential is limitless!" },
        { age: 45, quote: "Forty-five years old and thriving. Your resilience is your strength!" },
        { age: 46, quote: "Forty-six years old and building a life of purpose. Continue to pursue your passions!" },
        { age: 47, quote: "Forty-seven years old and embracing the journey. Your potential is limitless!" },
        { age: 48, quote: "Forty-eight years old and thriving. Your resilience is your strength!" },
        { age: 49, quote: "Forty-nine years old and building a life of purpose. Continue to pursue your passions!" },
        { age: 50, quote: "Fifty years old and fabulous! Celebrate the wisdom and experiences that define you." },
        { age: 51, quote: "Fifty-one years old and thriving. Your journey is uniquely yours!" },
        { age: 52, quote: "Fifty-two years old and flourishing. Your resilience is your strength!" },
        { age: 53, quote: "Fifty-three years old and building a life of purpose. Continue to pursue your passions!" },
        { age: 54, quote: "Fifty-four years old and embracing the journey. Your potential is limitless!" },
        { age: 55, quote: "Fifty-five years old and thriving. Your resilience is your strength!" },
        { age: 56, quote: "Fifty-six years old and building a life of purpose. Continue to pursue your passions!" },
        { age: 57, quote: "Fifty-seven years old and embracing the journey. Your potential is limitless!" },
        { age: 58, quote: "Fifty-eight years old and thriving. Your resilience is your strength!" },
        { age: 59, quote: "Fifty-nine years old and building a life of purpose. Continue to pursue your passions!" },
        { age: 60, quote: "Sixty years old and sensational! Celebrate the accomplishments and adventures of a life well-lived." },
        { age: 61, quote: "Sixty-one years old and thriving. Your journey is uniquely yours!" },
        { age: 62, quote: "Sixty-two years old and flourishing. Your resilience is your strength!" },
        { age: 63, quote: "Sixty-three years old and building a life of purpose. Continue to pursue your passions!" },
        { age: 64, quote: "Sixty-four years old and embracing the journey. Your potential is limitless!" },
        { age: 65, quote: "Sixty-five years old and thriving. Your resilience is your strength!" },
        { age: 66, quote: "Sixty-six years old and building a life of purpose. Continue to pursue your passions!" },
        { age: 67, quote: "Sixty-seven years old and embracing the journey. Your potential is limitless!" },
        { age: 68, quote: "Sixty-eight years old and thriving. Your resilience is your strength!" },
        { age: 69, quote: "Sixty-nine years old and building a life of purpose. Continue to pursue your passions!" },
        { age: 70, quote: "Seventy years old and still shining! Celebrate the richness of a life well-lived." },
        { age: 71, quote: "Seventy-one years old and thriving. Your journey is uniquely yours!" },
        { age: 72, quote: "Seventy-two years old and flourishing. Your resilience is your strength!" },
        { age: 73, quote: "Seventy-three years old and building a life of purpose. Continue to pursue your passions!" },
        { age: 74, quote: "Seventy-four years old and embracing the journey. Your potential is limitless!" },
        { age: 75, quote: "Seventy-five years old and thriving. Your resilience is your strength!" },
        { age: 76, quote: "Seventy-six years old and building a life of purpose. Continue to pursue your passions!" },
        { age: 77, quote: "Seventy-seven years old and embracing the journey. Your potential is limitless!" },
        { age: 78, quote: "Seventy-eight years old and thriving. Your resilience is your strength!" },
        { age: 79, quote: "Seventy-nine years old and building a life of purpose. Continue to pursue your passions!" },
        { age: 80, quote: "Eighty years old and still fabulous! Celebrate the achievements and wisdom of a life well-lived." },
        { age: 81, quote: "Eighty-one years old and thriving. Your journey is uniquely yours!" },
        { age: 82, quote: "Eighty-two years old and flourishing. Your resilience is your strength!" },
        { age: 83, quote: "Eighty-three years old and building a life of purpose. Continue to pursue your passions!" },
        { age: 84, quote: "Eighty-four years old and embracing the journey. Your potential is limitless!" },
        { age: 85, quote: "Eighty-five years old and thriving. Your resilience is your strength!" },
        { age: 86, quote: "Eighty-six years old and building a life of purpose. Continue to pursue your passions!" },
        { age: 87, quote: "Eighty-seven years old and embracing the journey. Your potential is limitless!" },
        { age: 88, quote: "Eighty-eight years old and thriving. Your resilience is your strength!" },
        { age: 89, quote: "Eighty-nine years old and building a life of purpose. Continue to pursue your passions!" },
        { age: 90, quote: "Ninety years of living! Celebrate the legacy of a life well-lived." },
        { age: 91, quote: "Ninety-one years old and thriving. Your journey is uniquely yours!" },
        { age: 92, quote: "Ninety-two years old and flourishing. Your resilience is your strength!" },
        { age: 93, quote: "Ninety-three years old and building a life of purpose. Continue to pursue your passions!" },
        { age: 94, quote: "Ninety-four years old and embracing the journey. Your potential is limitless!" },
        { age: 95, quote: "Ninety-five years old and thriving. Your resilience is your strength!" },
        { age: 96, quote: "Ninety-six years old and building a life of purpose. Continue to pursue your passions!" },
        { age: 97, quote: "Ninety-seven years old and embracing the journey. Your potential is limitless!" },
        { age: 98, quote: "Ninety-eight years old and thriving. Your resilience is your strength!" },
        { age: 99, quote: "Ninety-nine years old and building a life of purpose. Continue to pursue your passions!" },
        { age: 100, quote: "A century of life! Celebrate the remarkable journey and wisdom of a centenarian." },
        { n: 333,  quote: "Happy that you are still alive" },
        { non: 343,  quote: " Stay calm you are yet to born " },
        
      ];
      
      export default ageQuotes;
      